services:
  - type: web
    name: authentichain
    runtime: docker
    plan: free
    envVars:
      - key: PUBLIC_BASE_URL
        value: https://authentichain.website
      - key: FRONTEND_ORIGIN
        value: https://admin.authentichain.website
      - key: FRONTEND_ORIGINS
        value: https://admin.authentichain.website,https://authentichain-dashboard.onrender.com
      - key: DB_HOST
        fromDatabase:
          name: product-auth-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: product-auth-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: product-auth-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: product-auth-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: product-auth-db
          property: password
  - type: web
    name: authentichain-dashboard
    runtime: static
    rootDir: dashboard
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://authentichain.website

databases:
  - name: product-auth-db
    databaseName: product_auth
    user: product_auth
    plan: free
